Document: ubucompilator
Title: Debian ubucompilator Manual
Author: <insert document author here>
Abstract: This manual describes what ubucompilator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ubucompilator/ubucompilator.sgml.gz

Format: postscript
Files: /usr/share/doc/ubucompilator/ubucompilator.ps.gz

Format: text
Files: /usr/share/doc/ubucompilator/ubucompilator.text.gz

Format: HTML
Index: /usr/share/doc/ubucompilator/html/index.html
Files: /usr/share/doc/ubucompilator/html/*.html
